<?php

namespace AppBundle\Repository;

/**
 * FichaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaRepository extends \Doctrine\ORM\EntityRepository
{
}
