<?php

namespace AppBundle\Repository;

/**
 * TableroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableroRepository extends \Doctrine\ORM\EntityRepository
{
}
