<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Ficha;
use AppBundle\Entity\Tablero;

/**
 * TableroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableroRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Obtiene el número de fichas que hay puestas en un Tablero.
     *
     * @param Tablero $tablero
     * @return integer
     */
    public function getNumeroFichasPuestas(Tablero $tablero)
    {
        return count($tablero->getFichas());
    }

    /**
     * Genera una matriz con la disposición de las fichas de un Tablero por filas y por columnas.
     *
     * @param Tablero $tablero
     * @return [][]
     */
    public function getMatrizFichasPuestas(Tablero $tablero)
    {
        $fichas = $tablero->getFichas();
        $filasTablero = $tablero->getNumFilas();
        $columnasTablero = $tablero->getNumColumnas();

        $matrizFichas = [];

        //Generamos una matriz sobre la que poder colocar, y posteriormente acceder, de forma fácil las fichas de un tablero
        for ($i = 0; $i < $filasTablero; $i++) {
            for ($j = 0; $j < $columnasTablero; $j++) {
                $matrizFichas[$i][$j] = null;
            }
        }

        /* @var Ficha $ficha */
        foreach ($fichas as $ficha) {
            //Colocamos cada Ficha puesta en el Tablero sobre la matriz definida anteriormente
            $matrizFichas[$ficha->getPosFila()][$ficha->getPosColumna()] = $ficha;
        }

        return $matrizFichas;
    }
}
