<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Tablero;

/**
 * TableroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableroRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Obtiene el número de fichas que hay puestas en un Tablero.
     *
     * @param Tablero $tablero
     * @return integer
     */
    public function getNumeroFichasPuestas(Tablero $tablero)
    {
        return count($tablero->getFichas());
    }
}
