<?php

namespace AppBundle\Repository;

/**
 * TipoFichaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFichaRepository extends \Doctrine\ORM\EntityRepository
{
}
